#pragma once

void run_kernel_api_core_contract_tests();
void run_kernel_api_watcher_smoke_tests();
void run_attachment_diagnostics_tests();
void run_attachment_public_surface_tests();
void run_attachment_lifecycle_tests();
void run_chemistry_tests();
void run_crystal_compute_tests();
void run_symmetry_compute_tests();
void run_domain_surface_tests();
void run_domain_object_tests();
void run_domain_reference_tests();
void run_domain_diagnostics_tests();
void run_pdf_surface_tests();
void run_pdf_diagnostics_tests();
void run_product_compute_tests();
void run_ai_embedding_cache_tests();
void run_runtime_recovery_tests();
void run_search_public_surface_tests();
void run_search_expanded_tests();
void run_search_legacy_tests();
void run_rebuild_runtime_tests();
void run_runtime_diagnostics_tests();
